language: python

dist: trusty
sudo: required

os:
  - linux

python:
  - "2.7"

env:
  matrix:
    - TESTJDK="openjdk6"
    - TESTJDK="openjdk7"
    # bad javac ...
    #- TESTJDK="openjdk8"
    - TESTJDK="oraclejdk7"
    - TESTJDK="oraclejdk8"
    # cannot find -ljava
    #- TESTJDK="oraclejdk9"

matrix:
  include:
    # Add OSX builds separately because they don't support "language: python"
    # and also have  no jdk_switcher. Just using OSX defaults there ...
    - language: java
      os: osx
      osx_image: xcode7.3
      python: "dflt"
      env: TESTJDK="OSX 10.11 default" OSX_PY="2"
    - language: java
      os: osx
      osx_image: xcode8
      python: "dflt"
      env: TESTJDK="OSX 10.11 default" OSX_PY="2"
    - language: java
      os: osx
      osx_image: xcode8.1
      python: "dflt"
      env: TESTJDK="OSX 10.12 default" OSX_PY="2"
    - language: java
      os: osx
      osx_image: xcode8.2
      python: "dflt"
      env: TESTJDK="OSX 10.12 default" OSX_PY="2"
    - language: java
      os: osx
      osx_image: xcode7.3
      python: "dflt"
      env: TESTJDK="OSX 10.11 default" OSX_PY="3"
    - language: java
      os: osx
      osx_image: xcode8
      python: "dflt"
      env: TESTJDK="OSX 10.11 default" OSX_PY="3"
    - language: java
      os: osx
      osx_image: xcode8.1
      python: "dflt"
      env: TESTJDK="OSX 10.12 default" OSX_PY="3"
    - language: java
      os: osx
      osx_image: xcode8.2
      python: "dflt"
      env: TESTJDK="OSX 10.12 default" OSX_PY="3"

install:
  - source ./.travis-functions.sh
  - travis_have_sudo
  - travis_jdk_switcher
  - travis_show_env
  - travis_install_script

script:
  - travis_script

